import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@/cms/registry";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
  
export const metadata: Metadata = {
  title: "Demo: Banner Helath",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        {/*
          Optimizely Web Experimentation snippet. Loaded as a synchronous, render-
          blocking script at the top of <head> (no async/defer) so it executes
          before first paint and avoids experiment flicker — the intentional
          trade-off the no-sync-scripts lint rule warns about.
        */}
        {/* eslint-disable-next-line @next/next/no-sync-scripts */}
        <script src="https://cdn.optimizely.com/js/5950577065066496.js" />
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
